### ISSUE TITLE
Using for arrays? deleted seems to be wrong

### ISSUE THREAD

**Issue by giorgio79** [mattphillips/deep-object-diff#43] opened 2018-11-13 13:41 UTC
Tried using it for arrays, but it seems deleted items are tackled incorrectly. The script is not taking the shortest path.

eg https://runkit.com/giorgio79/5bead0643e02a00012ed51d0

```
const { diff, addedDiff, deletedDiff, detailedDiff, updatedDiff } = require("deep-object-diff");

const wrong = [
 "Tom",
 ",",
 "was",
 "involved",
 "in"
];

const right = [
 "Tom",
 "was",
 "involved",
 "in"
 ];

console.log(detailedDiff(wrong, right));
```

getting

```
Object
added: Object {}
deleted: Object {4: undefined}
updated: Object {1: "was", 2: "involved", 3: "in"}

```

I would have expected
Object
added: Object {}
deleted: Object {1: ","}
updated: Object {}

**Comment by drdreo** [comment] 2018-11-27 12:07
You are right. Even the documentation example can't distinguish deletes on the same property.  

This behavior is actually quiet reasonable. How would you distinguish between an update and a delete? Maybe this is even the desired behavior in some cases (queue data structure).

```
const lhs = {
  foo: {
    bar: {
      a: ['a', 'b','c'],
      b: 2,
      c: ['x', 'y'],
      e: 100 // deleted
    }
  },
  buzz: 'world'
};

const rhs = {
  foo: {
    bar: {
      a: ['a', 'c'], // index 1 ('b')  deleted
      b: 2, // unchanged
      c: ['x', 'y', 'z'], // 'z' added
      d: 'Hello, world!' // added
    }
  },
  buzz: 'fizz' // updated
};

console.log(detailedDiff(lhs, rhs));

// produces: foo.bar.a.1: 'c' -->  updated
// foo.bar.a.2: undefined -->  deleted
```

**Comment by devniel** [comment] 2019-03-24 02:18
got the same problem. is it a bug, right ?

**Comment by anko** [comment] 2019-04-01 06:08
I think this is and should continue to be the intended behaviour.

Reasoning, following @giorgio79's example:

The operation to get from

    [ "Tom", ",", "was", "involved", "in" ]

to

    [ "Tom", "was", "involved", "in" ]

is to shift everything else up 1 index to cover over the `","`.

That matches what the diff you see is telling you:

    added: Object {}
    deleted: Object {4: undefined}
    updated: Object {1: "was", 2: "involved", 3: "in"}

If it said this,

    added: Object {}
    deleted: Object {1: ","}
    updated: Object {}

that would imply the array should be transformed to

    [ "Tom", undefined, "was", "involved", "in" ]

which is a different array!

**Comment by r3wt** [comment] 2019-04-05 15:16
anko is correct, this is intended behavior.

**Comment by mattphillips** [comment] 2019-04-07 22:45
Gonna close this as it is the correct behaviour as @anko explains above.

Thanks @anko for taking the time to add a clear explanation 😄

**Closed by mattphillips** 2019-04-07 22:45 UTC
